### PR TITLE
add pep to synchronize databases between services

### PR DESCRIPTION
**Pull request by fblackburn1**

### CODE REVIEW

**Comment by pc-m** [comment]
My preferred solution is the fourth. The implementation details of the cron still need to be defined. For example, does the cron uses an API (that we need to implement) to DELETE /tenants on each services? does it delete stuff in the DB? does it import database stuff from each services (like purge db does)?

**Comment by sduthil** [comment]
Agreed, my preferred solution is 4. too.
I don't have a preference for the cron job implementation. A REST API `DELETE /caches` (or similar) seems the nicest, but I have no objections to other implementations.

**Comment by fblackburn1** [comment]
Not sure to understand your responses, there is no one-fit-all solution.
Ex: you cannot use 4 with presence (using cron to synchronize chatd and auth/asterisk/confd)

The question is more about: Do you agree on the conclusion? (avoid 1-2 and use 3-4 according the scenario)
I can refactor the conclusion to be more explicit about 1-2 and prioritize 4 over 3 if it works

**Comment by sduthil** [comment]
@fblackburn1, that's what I had in mind, thank you for expliciting.

**Comment by fblackburn1** [comment]
Done, do not hesitate to rephrase or improve :)

**Review by sduthil — APPROVED** [review]

**Pull request merged**
